#!/bin/sh

# ci_post_clone.sh
# Runs after Xcode Cloud clones the repository.
# Generates Secrets.xcconfig from Xcode Cloud environment variables.

set -e

SECRETS_FILE="$CI_PRIMARY_REPOSITORY_PATH/RecipeApp/Configuration/Secrets.xcconfig"

echo "Generating Secrets.xcconfig..."

cat > "$SECRETS_FILE" <<EOF
// Auto-generated by ci_post_clone.sh — do not edit
CLAUDE_API_KEY = ${CLAUDE_API_KEY}
EOF

echo "Secrets.xcconfig created at $SECRETS_FILE"
